import { PlaceType } from "./";

export interface NearbySearchBody {
  /**
   * Place details will be displayed with the preferred language if available. If the language code is unspecified or unrecognized, place details of any language may be returned, with a preference for English if such details exist.
   */
  languageCode?: string;
  /**
   * The Unicode country/region code (CLDR) of the location where the request is coming from. This parameter is used to display the place details, like region-specific place name, if available. The parameter can affect results based on applicable law.
   */
  regionCode?: string;
  /**
   * Included Place type (eg, "restaurant" or "gas_station") from https://developers.google.com/maps/documentation/places/web-service/place-types.
   */
  includedTypes?: IncludedExcludedType[];
  /**
   * Included Place type (eg, "restaurant" or "gas_station") from https://developers.google.com/maps/documentation/places/web-service/place-types.
   */
  excludedTypes?: IncludedExcludedType[];
  /**
   * Included Place type (eg, "restaurant" or "gas_station") from https://developers.google.com/maps/documentation/places/web-service/place-types.
   */
  includedPrimaryTypes?: IncludedExcludedType[];
  /**
   * Included Place type (eg, "restaurant" or "gas_station") from https://developers.google.com/maps/documentation/places/web-service/place-types.
   */
  excludedPrimaryTypes?: IncludedExcludedType[];
  /**
   * Maximum number of results to return. It must be between 1 and 20 (default), inclusively. If the number is unset, it falls back to the upper limit. If the number is set to negative or exceeds the upper limit, an INVALID_ARGUMENT error is returned.
   */
  maxResultCount?: integer;
  /**
   * Required. The region to search.
   */
  locationRestriction: LocationRestriction;
  /**
   * How results will be ranked in the response.
   */
  rankPreference?: "RANK_PREFERENCE_UNSPECIFIED" | "DISTANCE" | "POPULARITY";
}

export interface LocationRestriction {
  circle: CircleType;
}

export interface CircleType {
  center: {
    latitude: number;
    longitude: number;
  };
  radius?: number;
}
export type IncludedExcludedType =
  | "car_dealer"
  | "car_rental"
  | "car_repair"
  | "car_wash"
  | "electric_vehicle_charging_station"
  | "gas_station"
  | "parking"
  | "rest_stop"
  | "farm"
  | "art_gallery"
  | "museum"
  | "performing_arts_theater"
  | "library"
  | "preschool"
  | "primary_school"
  | "school"
  | "secondary_school"
  | "university"
  | "amusement_center"
  | "amusement_park"
  | "aquarium"
  | "banquet_hall"
  | "bowling_alley"
  | "casino"
  | "community_center"
  | "convention_center"
  | "cultural_center"
  | "dog_park"
  | "event_venue"
  | "hiking_area"
  | "historical_landmark"
  | "marina"
  | "movie_rental"
  | "movie_theater"
  | "national_park"
  | "night_club"
  | "park"
  | "tourist_attraction"
  | "visitor_center"
  | "wedding_venue"
  | "zoo"
  | "accounting"
  | "atm"
  | "bank"
  | "american_restaurant"
  | "bakery"
  | "bar"
  | "barbecue_restaurant"
  | "brazilian_restaurant"
  | "breakfast_restaurant"
  | "brunch_restaurant"
  | "cafe"
  | "chinese_restaurant"
  | "coffee_shop"
  | "fast_food_restaurant"
  | "french_restaurant"
  | "greek_restaurant"
  | "hamburger_restaurant"
  | "ice_cream_shop"
  | "indian_restaurant"
  | "indonesian_restaurant"
  | "italian_restaurant"
  | "japanese_restaurant"
  | "korean_restaurant"
  | "lebanese_restaurant"
  | "meal_delivery"
  | "meal_takeaway"
  | "mediterranean_restaurant"
  | "mexican_restaurant"
  | "middle_eastern_restaurant"
  | "pizza_restaurant"
  | "ramen_restaurant"
  | "restaurant"
  | "sandwich_shop"
  | "seafood_restaurant"
  | "spanish_restaurant"
  | "steak_house"
  | "sushi_restaurant"
  | "thai_restaurant"
  | "turkish_restaurant"
  | "vegan_restaurant"
  | "vegetarian_restaurant"
  | "vietnamese_restaurant"
  | "administrative_area_level_1"
  | "administrative_area_level_2"
  | "country"
  | "locality"
  | "postal_code"
  | "school_district"
  | "city_hall"
  | "courthouse"
  | "embassy"
  | "fire_station"
  | "local_government_office"
  | "police"
  | "post_office"
  | "dental_clinic"
  | "dentist"
  | "doctor"
  | "drugstore"
  | "hospital"
  | "medical_lab"
  | "pharmacy"
  | "physiotherapist"
  | "spa"
  | "bed_and_breakfast"
  | "campground"
  | "camping_cabin"
  | "cottage"
  | "extended_stay_hotel"
  | "farmstay"
  | "guest_house"
  | "hostel"
  | "hotel"
  | "lodging"
  | "motel"
  | "private_guest_room"
  | "resort_hotel"
  | "rv_park"
  | "church"
  | "hindu_temple"
  | "mosque"
  | "synagogue"
  | "barber_shop"
  | "beauty_salon"
  | "cemetery"
  | "child_care_agency"
  | "consultant"
  | "courier_service"
  | "electrician"
  | "florist"
  | "funeral_home"
  | "hair_care"
  | "hair_salon"
  | "insurance_agency"
  | "laundry"
  | "lawyer"
  | "locksmith"
  | "moving_company"
  | "painter"
  | "plumber"
  | "real_estate_agency"
  | "roofing_contractor"
  | "storage"
  | "tailor"
  | "telecommunications_service_provider"
  | "travel_agency"
  | "veterinary_care"
  | "auto_parts_store"
  | "bicycle_store"
  | "book_store"
  | "cell_phone_store"
  | "clothing_store"
  | "convenience_store"
  | "department_store"
  | "discount_store"
  | "electronics_store"
  | "furniture_store"
  | "gift_shop"
  | "grocery_store"
  | "hardware_store"
  | "home_goods_store"
  | "home_improvement_store"
  | "jewelry_store"
  | "liquor_store"
  | "market"
  | "pet_store"
  | "shoe_store"
  | "shopping_mall"
  | "sporting_goods_store"
  | "store"
  | "supermarket"
  | "wholesaler"
  | "athletic_field"
  | "fitness_center"
  | "golf_course"
  | "gym"
  | "playground"
  | "ski_resort"
  | "sports_club"
  | "sports_complex"
  | "stadium"
  | "swimming_pool"
  | "airport"
  | "bus_station"
  | "bus_stop"
  | "ferry_terminal"
  | "heliport"
  | "light_rail_station"
  | "park_and_ride"
  | "subway_station"
  | "taxi_stand"
  | "train_station"
  | "transit_depot"
  | "transit_station"
  | "truck_stop"
  | "administrative_area_level_3"
  | "administrative_area_level_4"
  | "administrative_area_level_5"
  | "administrative_area_level_6"
  | "administrative_area_level_7"
  | "archipelago"
  | "colloquial_area"
  | "continent"
  | "establishment"
  | "floor"
  | "food"
  | "general_contractor"
  | "geocode"
  | "health"
  | "intersection"
  | "landmark"
  | "natural_feature"
  | "neighborhood"
  | "place_of_worship"
  | "plus_code"
  | "point_of_interest"
  | "political"
  | "post_box"
  | "postal_code_prefix"
  | "postal_code_suffix"
  | "postal_town"
  | "premise"
  | "room"
  | "route"
  | "street_address"
  | "street_number"
  | "sublocality"
  | "sublocality_level_1"
  | "sublocality_level_2"
  | "sublocality_level_3"
  | "sublocality_level_4"
  | "sublocality_level_5"
  | "subpremise"
  | "town_square";

interface NearbySearchResponse {
  places: PlaceType[];
}

type FieldMaskNearbySearch =
  | "places.accessibilityOptions"
  | "places.addressComponents"
  | "places.adrFormatAddress"
  | "places.attributions"
  | "places.businessStatus"
  | "places.displayName"
  | "places.formattedAddress"
  | "places.googleMapsUri"
  | "places.iconBackgroundColor"
  | "places.iconMaskBaseUri"
  | "places.id"
  | "places.location"
  | "places.name"
  | "places.photos"
  | "places.plusCode"
  | "places.primaryType"
  | "places.primaryTypeDisplayName"
  | "places.shortFormattedAddress"
  | "places.subDestinations"
  | "places.types"
  | "places.utcOffsetMinutes"
  | "places.viewport"
  | "places.currentOpeningHours"
  | "places.currentSecondaryOpeningHours"
  | "places.internationalPhoneNumber"
  | "places.nationalPhoneNumber"
  | "places.priceLevel"
  | "places.rating"
  | "places.regularOpeningHours"
  | "places.regularSecondaryOpeningHours"
  | "places.userRatingCount"
  | "places.websiteUri"
  | "places.allowsDogs"
  | "places.curbsidePickup"
  | "places.delivery"
  | "places.dineIn"
  | "places.editorialSummary"
  | "places.evChargeOptions"
  | "places.fuelOptions"
  | "places.goodForChildren"
  | "places.goodForGroups"
  | "places.goodForWatchingSports"
  | "places.liveMusic"
  | "places.menuForChildren"
  | "places.parkingOptions"
  | "places.paymentOptions"
  | "places.outdoorSeating"
  | "places.reservable"
  | "places.restroom"
  | "places.reviews"
  | "places.servesBeer"
  | "places.servesBreakfast"
  | "places.servesBrunch"
  | "places.servesCocktails"
  | "places.servesCoffee"
  | "places.servesDessert"
  | "places.servesDinner"
  | "places.servesLunch"
  | "places.servesVegetarianFood"
  | "places.servesWine"
  | "places.takeout"
  | "*";
